spring:
  application:
    name: quix
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
supabase:
  username: postgres
  url: ${SUPABASE_URL}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  jwt-secret: ${SUPABASE_JWT_TOKEN}

