spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meinedb
    username: postgres
    password: deinPasswort
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
