spring:
  datasource:
    url: jdbc:postgresql://ep-cool-pond-agts1tb1-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_E5QOqwIU9yZC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # erzeugt Tabellen automatisch, kann bei produktiv auch "validate" sein
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
