spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?user=postgres.jscsxnjpkpsbvtdxihyn&password=Johannes8,12!20
    username: postgres.jscsxnjpkpsbvtdxihyn
    password: Johannes8,12!20
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update  # erzeugt Tabellen automatisch, kann bei produktiv auch "validate" sein
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
